### PR TITLE
Disable running hierarchical kernels by default

### PR DESCRIPTION
**Pull request by jopperm**

### CODE REVIEW

**Review by victor-eds — COMMENTED** [review]
Should this be set by default?

**Comment by jopperm** [comment]
> Should this be set by default?

Hmm, yes, that would be more convenient for us, but maybe easier to upstream if it's off by default.

**Review by sommerlukas — APPROVED** [review]
Implementation looks fine, but I agree with @victor-eds that not running hierarchical kernels should be the default behavior on this branch, as we know that hierarchical isn't supported by the MLIR-based compiler.

**Review by victor-eds — APPROVED** [review]

**Review by whitneywhtsang — APPROVED** [review]
Please rebase from latest sycl-mlir.
Do you plan to upstream this change?

**Comment by whitneywhtsang** [comment]
Added new label `upstream` in this repo to indicate PRs that we want to upstream.

**Comment by jopperm** [comment]
> Please rebase from latest sycl-mlir.

Done.

> Do you plan to upstream this change?

Potentially the addition of `shouldRunHierarchicalKernels()`, but not disabling it by default.

**Pull request merged**
